  
version: '2'

services:
  cherlockplease:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: cherlockplease
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
